// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imutfzhrabtylacldxhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltdXRmemhyYWJ0eWxhY2xkeGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTI5MTksImV4cCI6MjA3MDI2ODkxOX0.PRUssJYu_xfdpca1eV-C9Z3vIez1L3N-5s10D1kmhOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});